### ISSUE TITLE
Crashing randomly on blog with large number of likes

### ISSUE THREAD

**Issue by mgdevereux** [andresdavid90/tumblr-lks-downldr-cli#3]
The script is crashing at different stages as it is loading all the urls into memory for a blog with a large number of likes. Sometimes it happens at 100 and sometimes it goes to over 30000. I am using it on Ubuntu Studio with node.js v4

**Comment by andrscrrn** [comment]
@mgdevereux In order to identify the issue, the best way would be running the code of `tumblr-lks-downldr` directly (cloning the repo and running the index.js file as a dependency) to really see the issue, since `tumblr-lks-downldr-cli` is just a wrapper of the module that I just mentioned.

Are you familiar with js coding? Maybe you can help me identifying the issue on your environment since I'm using it with my Tumblr blog and it seems to be working fine with big numbers.

**Comment by mgdevereux** [comment]
Sorry I haven't a clue about js. I'm only really familiar with matlab and if I could generate a list of urls then I would be very happy as matlab can do the rest. Thanks for your help so far, I have made some progress with using script in the terminal but I am having a strange redundancy issue where each url is generated approx 20 times and I'm not getting anywhere near a complete url list

**Comment by andrscrrn** [comment]
@mgdevereux I just released a new version. Can you please try it again? If it doesn't work, please provide as much info you can.
