### ISSUE TITLE
Crashing while downloading about 30.000 likes.

### ISSUE THREAD

**Issue by quetsch** [andresdavid90/tumblr-lks-downldr-cli#4]
Hi!
I am trying to download the favorites for a buddy from his public url. (https://www.tumblr.com/liked/by/fotosvondir). The script tells me Posts to load: 29986. If I run it with -l 30000, it will start over and over again, and after 5-10 restarts it will cancel without an error message and without downloading any pics.
I tried it with lower numbers. But I only had success if I scale down to under 10000. Is there any way to fix it? Could I provide you with more information?
Thank you in advance for any response.

**Comment by zooks** [comment]
Yep, it works well but occasionally stops when the number of liked posts is more than 1000.

**Comment by andrscrrn** [comment]
Hey @quetsch! Thanks for the information. I'm currently testing the blog that you provided `fotosvondir.tumblr.com` using a very fast connection just to see what happens. From my experience, with very large sets of images the utility with never finish and it's because somehow some downloads are failing silently. I'm still investigating the issue but, can you please provide information about the machine that is experiencing this issue?

**Comment by andrscrrn** [comment]
@quetsch Looking deeper, it is failing always in the image number 3954 but just using the `fotosvondir.tumblr.com` url. I tried with `andresdavid90.tumblr.com` and we can get more than that so, now I need to debug the code to find out what is the problem with that specific image that is breaking the module. I'll keep you updated.

**Comment by zooks** [comment]
@andresdavid90 Your script worked much faster than the other one written in Ruby. But it also crashes on second thousand of photos. Changing API key didn't help.

**Comment by andrscrrn** [comment]
@rpre can you please provide more info about in which circumstances it's crashing?

**Comment by zooks** [comment]
@andresdavid90 When I don't set the number of photos to download, it crashes before 1000 pics is downloaded. When I set "-l 4000" it crashes after about ~1500 pics. The script just stops without any warnings.

**Comment by andrscrrn** [comment]
@rpre with what blog?

**Comment by zooks** [comment]
@andresdavid90 Sorry, I can't give a link. BTW Ruby script crashed too with different amount of pics.

**Comment by quetsch** [comment]
Hi!
Thank you for your answer. I tried it on serveral machines with the same result (Ubuntu 12.04 64-bit and 14.04 64-bit). Both located in Germany with different ISPs and >200 Mbit/s download speed.
But as you mentioned above it might very likely be a problem with a specific image. Thx for researching!

**Comment by iampixel** [comment]
Hello and thank you for the module !
I'm having a similar problem here, download always fails on the same image (1044 or something), stuck at 7%
I also noticed that the downloads start in chronological order (latest liked post first) and suddenly (after the 20th like) skips to an "nth image" (I didn't manage to find where it is among 10 000 + posts). This doesn't seem to happen on your blog, and does happen on quetsch's around image 43 or so. 
I hope these information were relevant and can help you solve the problem.

Mac OS 10.11.4

**Comment by kasalana** [comment]
Hi, 
Sorry I know nothing about programming and this is the error I got when I try to run it. 

/usr/local/lib/node_modules/tumblr-lks-downldr-cli/node_modules/tumblr-lks-downldr/src/index.js:140
      throw err;
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)

hope this may help.
MAC OS 10.11.5

with regards.

**Comment by ghost** [comment]
I get the same error as well with a url of my own.

**Comment by VegaDeftwing** [comment]
Same here at kunke.tumblr.com ; trying only 1k it doesn't have an issue, but anymore and it fails. A lot of my likes are NSFW btw, so I'd advise against checking my blog.

**Comment by andrscrrn** [comment]
Ok, I've been checking this issue the whole day and I have this:
1. The [Tumblr API](https://www.tumblr.com/docs/en/api/v2#blog-likes) is providing a `liked_count` number that is unreachable since at some point after keep hitting the **likes** endpoint, it starts to send zero `liked_posts`. I already sent an email regarding this issue and I'm waiting for response.
2. Because of the first issue, we were getting duplicated entries making the user thinks that the utility would download more files but at the end just getting a lower number of liked posts downloaded.
3. Because of 1 and 2, users got very frustrated thinking about never reaching the goal number. I'm going to work in some kind of user feedback, letting the users know what is the real number of posts and images that are actually available for download.

For now, I'm going to keep this issue opened until I get some feedback from the Tumblr team.

**Comment by andrscrrn** [comment]
I just published the `2.1.6` version of the module. This should tell the user when a number of posts are unreachable because of the Tumblr API limitations. Closing this.

**Comment by VegaDeftwing** [comment]
In the future, is there a chance this will be updated so that it can either work around the api limitations (adding an hour delay after the first failed request?) or that Tumblr, will respond and allow for full downloads?

**Comment by andrscrrn** [comment]
I mean, there is always a change of Tumblr updating their API, but is totally out of our control and there is not any work around right now for this. Sorry... Is their fault... 😭
